# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    working_directory: ~/cci-legereme
    docker:
      # specify the version here
      - image: circleci/elixir:1.6.6
      - image: postgres:9.5
        environment:
          - POSTGRES_USER=ubuntu
          # - POSTGRES_DB=legereme
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
     # - run: mix ecto.create
     # - run: mix test

deployment:
  master:
    branch: master
    commands:
      - echo 'deploying master branch'
      - ssh -v $DROPLET_USER@$DROPLET_IP "cd ~/iphod-server; ./circle_deployer.sh"