use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :iphod, Iphod.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [  scheme: "http",
          host: "legereme.com", 
          port: 80
       ],
# #  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: System.get_env("SECRET_KEYBASE"),
  server: true
# 
# # Do not print debug messages in production
# config :logger, level: :info
# 
# # ## SSL Support
# #
# # To get SSL working, you will need to add the `https` key
# # to the previous section and set your `:url` port to 443:
# #
# config :iphod, Iphod.Repo,
#   adapter: Ecto.Adapters.Postgres,
#   username: ${"DB_USER"},
#   password: ${"DB_PASSWORD"},
#   database: ${"DB_NAME"},
#   hostname: ${"DB_HOSTNAME"},
#   url: System.get_env("DB_URL")[host: "example.com", port: 443],
#   pool_size: 10

config :iphod,    Iphod.Repo,
       adapter:   Ecto.Adapters.Postgres,
       hostname:  System.get_env("DB_HOSTNAME"),
       username:  System.get_env("DB_USER"),
       password:  System.get_env("DB_PASSWORD"),
       database:  System.get_env("DB_NAME"),
       pool_size: 10
# 
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :iphod, Iphod.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
##
#     config :iphod, Iphod.Endpoint, 
#     server: true,
#     http: [port: 8888],
#     url: [host: "legereme.com"],
#     root: ".",
#     cache_static_manifest: "priv/static/manifest.json",
#     server: true,
#     version: "0.0.1" # Mix.Project.config[:version]
#
#
# You will also need to set the application root to `.` in order
# for the new static assets to be served after a hot upgrade:
#
#     config :iphod, Iphod.Endpoint, root: "."

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
